config/routes.rb
Rails.application.routes.draw do
  root 'cep#index'
  get 'cep', to: 'cep#index'
  post 'cep', to: 'cep#cep'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'cepjs', to: 'cepjs#index'
  get 'zipcode', to: 'cepjs#show'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cep.rb
require 'net/http'
class CEP
	attr_accessor :logradouro, :bairro, :localidade, :uf, :error

	def initialize(cep)
		cep_encontrado = encontrar(cep) #hash
		preencher_dados(cep_encontrado) unless @error
	end


	private

	def encontrar(cep)
		begin
		ActiveSupport::JSON.decode(
			Net::HTTP.get(
				URI("https://viacep.com.br/ws/#{cep}/json/")
			)
		)
		rescue ActiveSupport::JSON.parse_error
			@error = "Cep não encontrado"
		end
	end

	def preencher_dados(cep_encontrado)
		@logradouro = cep_encontrado["logradouro"]
		@bairro = cep_encontrado["bairro"]
		@localidade = cep_encontrado["localidade"]
		@uf = cep_encontrado["uf"]
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cep_controller.rb
class CepController < ApplicationController

  def index
  end
  
  def cep
    cep = CEP.new(cep_params[:cep])
    @cep = cep_params[:cep]
    @logradouro = cep.logradouro
    @bairro = cep.bairro
    @localidade = cep.localidade
    @uf = cep.uf
    @error = cep.error
    render 'index'
  end

  private

  def cep_params
    params.permit(:cep)
  end


end

app/controllers/cepjs_controller.rb
class CepjsController < ApplicationController
  def show
    @cep = CEP.new(params[:cep])
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cep_helper.rb
module CepHelper
end

app/helpers/cepjs_helper.rb
module CepjsHelper
end

app/views/cep/index.html.erb
<nav class="navbar navbar-light bg-light mb-4">
			<div class="container">
				<div class="navbar-brand mb-0 h1">
					<h3>App Pesquisa Endereço</h3> 
				</div>
			</div>
		</nav>

		<div class="container">
            <%= form_with(url: cep_path, local: true) do |form| %>
                <div class="row form-group">
				<div class="col-sm-3">
                    <%= form.text_field :cep, class:"form-control", placeholder:"CEP", value: "#{@cep if  @cep}", onblur:"getDadosEnderecoPorCEP()" %>
				</div>
				<div class="col-sm-9">
					<input type="text" class="form-control" placeholder="Endereço" id="endereco" value="<%= @logradouro if  @logradouro  %>" readonly />
				</div>
			</div>

			<div class="row form-group">
				<div class="col-sm-6">
					<input type="text" class="form-control" placeholder="Bairro" id="bairro" value="<%= @bairro if  @bairro  %>" readonly />
				</div>
				<div class="col-sm-4">
					<input type="text" class="form-control" placeholder="Cidade" id="cidade" value="<%= @localidade if  @localidade  %>" readonly />
				</div>

				<div class="col-sm-2">
					<input type="text" class="form-control" placeholder="UF" id="uf" value="<%= @uf if  @uf  %>" readonly />
				</div>
                <button style="display: none;" type="submit" class="btn btn-primary" id="botao">Submit</button>
			<% end %>
		</div>

       <div style="color:red;"> <%= @error %> </div>


        <script> 
        
            function getDadosEnderecoPorCEP(){
                $('#botao').click()
            }

	   </script>

app/views/cepjs/index.html.erb
  
<nav class="navbar navbar-light bg-light mb-4">
			<div class="container">
				<div class="navbar-brand mb-0 h1">
					<h3>App JAVASCRIPT</h3>
				</div>
			</div>
		</nav>

		<div class="container">
			<div class="row form-group">
				<div class="col-sm-3">
					<input type="text" class="form-control" placeholder="CEP" id="cepinput"  />
				</div>
				<div class="col-sm-9">
					<input type="text" class="form-control" placeholder="Endereço" id="endereco" readonly />
				</div>
			</div>

			<div class="row form-group">
				<div class="col-sm-6">
					<input type="text" class="form-control" placeholder="Bairro" id="bairro" readonly />
				</div>
				<div class="col-sm-4">
					<input type="text" class="form-control" placeholder="Cidade" id="cidade" readonly />
				</div>

				<div class="col-sm-2">
					<input type="text" class="form-control" placeholder="UF" id="uf" readonly />
				</div>
			</div>
            <%= link_to "buscar", zipcode_path, remote:true, class:"btn btn-primary", id:"botao" %>
		</div>

       <script>
			$(document).ready(function(){

				$("#cepinput").change(function(){
					$("#botao").attr("href", "<%= zipcode_path %>/?cep="+$("#cepinput").val());
				});
			});
      </script>

app/views/cepjs/show.js.erb
$("#endereco").val("<%= @cep.logradouro %>");
$("#bairro").val("<%= @cep.bairro %>");
$("#cidade").val("<%= @cep.localidade%>");
$("#uf").val("<%= @cep.uf%>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= yield %>
  </body>


</html>